### PR TITLE
Make configure method public

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**
This method will now be called in the init process, based on the last configured version

### CODE REVIEW

**Comment by sosthene-nitrokey** [comment]
This PR also replaces #29

**Comment by robin-nitrokey** [comment]
For the filesystem versions we just use an integer which is easier to handle than the crate version.  Would that make sense in this case too?

**Comment by sosthene-nitrokey** [comment]
We could, but that seemed less error prone. The filesystem was versioned because it batches migrations from multiple backends at the same time, and filesystem migrations are much more expensive/risky than SE050 re-configuration

**Review by robin-nitrokey — APPROVED** [review]
Okay, if you thing this is easier than let’s do it that way.  For me the main argument for a counter would have been that we currently don’t always bump the crate version for every change.  This is especially true for testing, but also for the regular firmware.  So if you want to test changes, you need to bump the crate version every time instead of just changing a counter.

**Comment by sosthene-nitrokey** [comment]
Right. it's true that we generally bump the version number only very late in the development cycle.

**Comment by sosthene-nitrokey** [comment]
Maybe the struct could also be a bitflag of configured curves. This could also make future configure calls faster, by only configuring non-configured curves.

**Comment by robin-nitrokey** [comment]
I’m fine with both approaches.  I would default to using a counter because it is simpler, the additional work to re-initialize curves is negligible and it gives us more flexibility if we need to change the configuration more fundamentally than just adding curves.

**Pull request merged**
